<a href="https://colab.research.google.com/github/nabilah-afrin/recommendation_system_rokomri_books/blob/secondary/notebooks/preprocessing_bn_books.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# %cd /content/drive/MyDrive/Rokomari Recommendation Dataset
%cd /content/drive/MyDrive/Dataset/rokomari_books/Rokomari Recommendation Dataset/Datasets

/content/drive/.shortcut-targets-by-id/1SdeIcOv6xY-c8y2UcMwPLYx_BaB0zdXx/Rokomari Recommendation Dataset/Datasets

In [ ]:
!ls

 corrected_language.csv        rokomari_book_data_v2.csv	  'scraping log.txt'
'Data Analysis Report.gdoc'    rokomari_books_only_bangla_v2.csv   wrong_language_url.txt
 mixed_title_rokomari_v2.csv   rokomari_v2.csv
 rokomari_book_data.csv        rokomari_v2.ipynb

In [ ]:
# !pip install googletrans==4.0.0-rc1

In [ ]:
!pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 42.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from langdetect) (1.16.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993222 sha256=f9df40f25694016803faf06982ffe30cf2b37f0155b250b700f299f9067fa07a
  Stored in directory: /root/.cache/pip/wheels/95/03/7d/59ea870c70ce4e5a370638b5462a7711ab78fba2f655d05106
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [ ]:
!pip install deep_translator --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 2.6 MB/s eta 0:00:00

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import langdetect as ld
# import googletrans as gt
import deep_translator as dt
from deep_translator import GoogleTranslator

# Only Bangla Books

In [ ]:
# load the rokomari_bn_books.csv
# uncomment when loading from your drive
# df_bn = pd.read_csv("/content/drive/MyDrive/Rokomari Recommendation Dataset/df_bn.csv")

df_bn = pd.read_csv("rokomari_books_only_bangla_v2.csv")

In [ ]:
df_bn.head(5)

,book_id,title,author,publisher,publisher_name_english,categories,category_english,edition,isbn,summary,...,offer_price,book_url,prod_img_link,availability,product_category,actual_rating,bangla_title,language_title,language_categories,categories_fixed
0,350167,অমানুষিক,মনোরঞ্জন ব্যাপারী,একা,Eka (India),পশ্চিমবঙ্গের বই,West Bengal Books,6 March 2023,9789357762298,No summary,...,450.0,https://www.rokomari.com/book/350167/amanushik,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,অমানুষিক,bn,bn,পশ্চিমবঙ্গের বই
1,377700,নির্বাচিত গল্প সংকলন,লু স্যুন,ছাড়পত্র প্রকাশন (ইন্ডিয়া),Charpatra Prakashan (India),পশ্চিমবঙ্গের বই: সমকালীন গল্প,West Bengal Books: Contemporary Story,Edition,9788194097303,No summary,...,320.0,https://www.rokomari.com/book/377700/nirbachit...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,নির্বাচিত গল্প সংকলন,bn,bn,"পশ্চিমবঙ্গের বই, সমকালীন গল্প"
2,377718,তিমুর ও তার দলবল,আর্কাদি গাইদার,ছাড়পত্র প্রকাশন (ইন্ডিয়া),Charpatra Prakashan (India),পশ্চিমবঙ্গের বই: শিশু-কিশোর উপন্যাস,West Bengal Books: Children and Teens Novel,Edition,9788193860939,No summary,...,180.0,https://www.rokomari.com/book/377718/timur-o-t...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,তিমুর ও তার দলবল,bn,bn,"পশ্চিমবঙ্গের বই, শিশু-কিশোর উপন্যাস"
3,189529,চেক ডিসঅনার মামলার সহজ ভাষ্য,মোঃ কাইছার হামিদ,এ.কে লিগ্যাল সল্যুশন,A.K Legal Solution,ব্যাংকিং এন্ড কমার্স ল,Banking and Commerce Law,1st Published,No ISBN,* চেক ডিসঅনার ও মামলা দায়েরের পদ্ধতি সংক্রান্...,...,175.0,https://www.rokomari.com/book/189529/cheque-di...,https://img.cf.rokomari.com/ProductNew20190903...,Not Available,book,5.0,চেক ডিসঅনার মামলার সহজ ভাষ্য,bn,bn,ব্যাংকিং এন্ড কমার্স ল
4,325781,হাইকোর্ট এক্সাম ফর্মুলা,মোঃ কাইছার হামিদ,A.K Legal Solution,A.K Legal Solution,অ্যাডভোকেসি/বিচার আইন,Advocacy/ Adjudication Law,Edition,9789843545589,"""High Court Exam Formula"" book will be very he...",...,500.0,https://www.rokomari.com/book/325781/high-cour...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,হাইকোর্ট এক্সাম ফর্মুলা,bn,bn,"অ্যাডভোকেসি, বিচার আইন"

In [ ]:
def detect_language(row):
    try:
        lang = ld.detect(str(row))
    except:
        return 'unknown'
    return lang

In [ ]:
df_bn['language_author'] = df_bn['author'].apply(detect_language)

In [ ]:
df_bn.head()

,book_id,title,author,publisher,publisher_name_english,categories,category_english,edition,isbn,summary,...,book_url,prod_img_link,availability,product_category,actual_rating,bangla_title,language_title,language_categories,categories_fixed,language_author
0,350167,অমানুষিক,মনোরঞ্জন ব্যাপারী,একা,Eka (India),পশ্চিমবঙ্গের বই,West Bengal Books,6 March 2023,9789357762298,No summary,...,https://www.rokomari.com/book/350167/amanushik,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,অমানুষিক,bn,bn,পশ্চিমবঙ্গের বই,bn
1,377700,নির্বাচিত গল্প সংকলন,লু স্যুন,ছাড়পত্র প্রকাশন (ইন্ডিয়া),Charpatra Prakashan (India),পশ্চিমবঙ্গের বই: সমকালীন গল্প,West Bengal Books: Contemporary Story,Edition,9788194097303,No summary,...,https://www.rokomari.com/book/377700/nirbachit...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,নির্বাচিত গল্প সংকলন,bn,bn,"পশ্চিমবঙ্গের বই, সমকালীন গল্প",bn
2,377718,তিমুর ও তার দলবল,আর্কাদি গাইদার,ছাড়পত্র প্রকাশন (ইন্ডিয়া),Charpatra Prakashan (India),পশ্চিমবঙ্গের বই: শিশু-কিশোর উপন্যাস,West Bengal Books: Children and Teens Novel,Edition,9788193860939,No summary,...,https://www.rokomari.com/book/377718/timur-o-t...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,তিমুর ও তার দলবল,bn,bn,"পশ্চিমবঙ্গের বই, শিশু-কিশোর উপন্যাস",bn
3,189529,চেক ডিসঅনার মামলার সহজ ভাষ্য,মোঃ কাইছার হামিদ,এ.কে লিগ্যাল সল্যুশন,A.K Legal Solution,ব্যাংকিং এন্ড কমার্স ল,Banking and Commerce Law,1st Published,No ISBN,* চেক ডিসঅনার ও মামলা দায়েরের পদ্ধতি সংক্রান্...,...,https://www.rokomari.com/book/189529/cheque-di...,https://img.cf.rokomari.com/ProductNew20190903...,Not Available,book,5.0,চেক ডিসঅনার মামলার সহজ ভাষ্য,bn,bn,ব্যাংকিং এন্ড কমার্স ল,bn
4,325781,হাইকোর্ট এক্সাম ফর্মুলা,মোঃ কাইছার হামিদ,A.K Legal Solution,A.K Legal Solution,অ্যাডভোকেসি/বিচার আইন,Advocacy/ Adjudication Law,Edition,9789843545589,"""High Court Exam Formula"" book will be very he...",...,https://www.rokomari.com/book/325781/high-cour...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,হাইকোর্ট এক্সাম ফর্মুলা,bn,bn,"অ্যাডভোকেসি, বিচার আইন",bn

In [ ]:
df_bn['language_author'].value_counts()

language_author
bn    204248
ar       296
en        11
id         7
af         5
fr         1
tr         1
sv         1
so         1
nl         1
Name: count, dtype: int64

# Correcting author names

In [ ]:
# There are no rows with 'No Author' "

df_bn.loc[df_bn['author'] == 'No Author'].shape

(0, 26)

In [ ]:
# df_bn = df_bn.loc[~(df_bn['author'] == 'No Author')]

In [ ]:
# Deletion successful

# df_bn.loc[df_bn['author'] == 'No Author'].shape

In [ ]:
translator = GoogleTranslator(source='auto', target='bn')
text = "Saifur Rahman Khan"
translation = translator.translate(text=text)
translation

'সাইফুর রহমান খান'

In [ ]:
import re

def correct_author_names(row):
    """
    The unicode range between \u0980 - \u09FF defines the Bangla characters
    and digits in the Unicode character set
    """
    return re.sub(r'[^\u0980-\u09FF ]+', '', str(row)).strip()

def translate_author_names(row):
    text = str(row)
    translator = gt.Translator()
    translation = translator.translate(text=text, dest='bn')

    return translation.text

def translate_to_bangla(row):
    return GoogleTranslator(source='auto', target='bn').translate(text=str(row))

def translate_from_id(row):
    return GoogleTranslator(source='en', target='bn').translate(text=str(row))

In [ ]:
for language in df_bn['language_author'].value_counts().index:
    if language == 'bn' or language == 'ar':
        continue
    else:
        print(f"Correcting Language: {language}")
        filt = (df_bn['language_author'] == language, 'author')
        df_bn.loc[filt] = df_bn.loc[filt].apply(translate_to_bangla)

print("\nDone")

Correcting Language: en
Correcting Language: id
Correcting Language: af
Correcting Language: fr
Correcting Language: tr
Correcting Language: sv
Correcting Language: so
Correcting Language: nl

Done

## Let's see the value counts of the author_languages again

In [ ]:
df_bn['language_author'] = df_bn['author'].apply(detect_language)

In [ ]:
df_bn['language_author'].value_counts()

language_author
bn    204274
ar       288
en         6
id         3
tr         1
Name: count, dtype: int64

In [ ]:
df_bn.loc[df_bn['language_author'] == 'en']

,book_id,title,author,publisher,publisher_name_english,categories,category_english,edition,isbn,summary,...,book_url,prod_img_link,availability,product_category,actual_rating,bangla_title,language_title,language_categories,categories_fixed,language_author
20731,228238,"ডিজিটাল ব্যাংক, নিও ব্যাংক : ভবিষ্যৎ ব্যাংকিং","ড. জাহিদুজ্জামান, CIPA, CSAA, CIFE ( Certified...",তাম্রলিপি,Tamrolipi,ব্যাংকিং ও ফিন্যান্স,Banking and Finance,1st Edition,No ISBN,সামনের দুনিয়া প্রযুক্তিময় দুনিয়া। প্রযুক্তি...,...,https://www.rokomari.com/book/228238/digital-b...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,5.0,ডিজিটাল ব্যাংক নিও ব্যাংক : ভবিষ্যৎ ব্যাংকিং,bn,bn,"ব্যাংকিং, ফিন্যান্স",en
147551,284249,ইসলামী ব্যাংকিং এবং ফাইন্যান্সঃ মূলনীতি ও অনুশীলন,"ড. জাহিদুজ্জামান, CIPA, CSAA, CIFE ( Certified...",ব্রেইনারি পাবলিকেশন,Brainery Publication,ইসলামি অর্থনীতি ও ব্যবসা বাণিজ্য,Islamic Financial and Business,1st Edition 2023,978-984-96702-4-7,রাসুল (সা:) এর যুগ থেকে শুরু করে সাহাবায়ে কেরা...,...,https://www.rokomari.com/book/284249/islamic-b...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,ইসলামী ব্যাংকিং এবং ফাইন্যান্সঃ মূলনীতি ও অনুশীলন,bn,bn,"ইসলামি অর্থনীতি, ব্যবসা বাণিজ্য",en
147552,283901,ইসলামিক ফিনটেক,"ড. জাহিদুজ্জামান, CIPA, CSAA, CIFE ( Certified...",ব্রেইনারি পাবলিকেশন,Brainery Publication,ইসলামি অর্থনীতি ও ব্যবসা বাণিজ্য,Islamic Financial and Business,1st Published,9789849670223,মুসলিম জনগণ ডিজিটাল ফিন্যান্স এবং শারিয়াহ নীত...,...,https://www.rokomari.com/book/283901/islamic-f...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,ইসলামিক ফিনটেক,bn,bn,"ইসলামি অর্থনীতি, ব্যবসা বাণিজ্য",en
147553,283891,ফিনটেক,"ড. জাহিদুজ্জামান, CIPA, CSAA, CIFE ( Certified...",ব্রেইনারি পাবলিকেশন,Brainery Publication,ব্যাংকিং ও ফিন্যান্স,Banking and Finance,3rd Published,9789849670230,আর্থিক (ফাইন্যান্সিয়াল) খাতে প্রযুক্তির (টেকনো...,...,https://www.rokomari.com/book/283891/fintech,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,ফিনটেক,bn,bn,"ব্যাংকিং, ফিন্যান্স",en
163435,113205,স্বপ্ন সুন্দর ভালবাসা,Josim Chowdhury(জসিম চৌধুরী)-12455,বলাকা প্রকাশন (চট্টগ্রাম),Balaka Prokashon (Chittagong),বাংলা কবিতা,Poem- Bangla,1st Published,9789849161752,No summary,...,https://www.rokomari.com/book/113205/swapno-su...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,স্বপ্ন সুন্দর ভালবাসা,bn,bn,বাংলা কবিতা,en
203731,339170,"অটিজম বাংলাদেশ প্রেক্ষিত, সাফল্য ও সম্ভাবনা",Josim Chowdhury(জসিম চৌধুরী)-12455,ঝুমঝুমি প্রকাশন,Zhumzhumi prokashan,শারীরিক ও মানসিক প্রতিবন্ধকতা,Physical and Mental Disorder,1st Edition,9789849748199,লেখক জসিম চৌধুরী তার গ্রন্থে যেমন বৈশ্বিক অটিজ...,...,https://www.rokomari.com/book/339170/autism-ba...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,অটিজম বাংলাদেশ প্রেক্ষিত সাফল্য ও সম্ভাবনা,bn,bn,"শারীরিক, মানসিক প্রতিবন্ধকতা",en

In [ ]:
df_bn.loc[df_bn['language_author'] == 'tr']

,book_id,title,author,publisher,publisher_name_english,categories,category_english,edition,isbn,summary,...,book_url,prod_img_link,availability,product_category,actual_rating,bangla_title,language_title,language_categories,categories_fixed,language_author
44759,408265,বহুমাত্রিক রবীন্দ্রনাথ,Prabir Kumar Pal,রিভার্স পাবলিকেশন,Reverse Publication,পশ্চিমবঙ্গের বই: প্রবন্ধ,West Bengal Books: Articles,Edition,9789392283093,No summary,...,https://www.rokomari.com/book/408265/bohumatri...,https://img.cf.rokomari.com/ProductNew20190903...,Request for Stock,book,0.0,বহুমাত্রিক রবীন্দ্রনাথ,bn,bn,"পশ্চিমবঙ্গের বই, প্রবন্ধ",tr

In [ ]:
df_bn.loc[df_bn['language_author'] == 'id']

,book_id,title,author,publisher,publisher_name_english,categories,category_english,edition,isbn,summary,...,book_url,prod_img_link,availability,product_category,actual_rating,bangla_title,language_title,language_categories,categories_fixed,language_author
163,417530,ইশ্বর আসছেন,Joydeep Lahiri,অক্ষর সংলাপ প্রকাশন,Akshar Sanglap Prakashan (India),পশ্চিমবঙ্গের বই,West Bengal Books,No Edition,No ISBN,No summary,...,https://www.rokomari.com/book/417530/iswar-aschen,https://img.cf.rokomari.com/ProductNew20190903...,Request for Stock,book,0.0,ইশ্বর আসছেন,bn,bn,পশ্চিমবঙ্গের বই,id
54633,283863,স্থান কাল মহাকর্ষ ও অপেক্ষবাদ,Biswaranjan Nag,পশ্চিমবঙ্গ রাজ্য পুস্তক পর্ষৎ (ভারত),Poshcimbongo Rajjo Pustok Porshot (India),পশ্চিমবঙ্গের বই,West Bengal Books,1st published,8124702535,No summary,...,https://www.rokomari.com/book/283863/sthan-kal...,https://img.cf.rokomari.com/ProductNew20190903...,Request for Stock,book,0.0,স্থান কাল মহাকর্ষ ও অপেক্ষবাদ,bn,bn,পশ্চিমবঙ্গের বই,id
200740,415552,মণিমালা,Prasanta Kumar Bhowmik,ঋক পাব্লিকেশন,Rick Publications,পশ্চিমবঙ্গের বই,West Bengal Books,Edition,978819578212,No summary,...,https://www.rokomari.com/book/415552/monimala,https://img.cf.rokomari.com/ProductNew20190903...,Request for Stock,book,0.0,মণিমালা,bn,bn,পশ্চিমবঙ্গের বই,id

In [ ]:
# changing manually the author name Prabir Kumar Pal (সম্পাদক) to প্রবীর কুমার পাল

df_bn.loc[df_bn['author'] == 'Prabir Kumar Pal', 'author'] = 'প্রবীর কুমার পাল'

In [ ]:
df_bn['language_author'] = df_bn['author'].apply(detect_language)

In [ ]:
df_bn['language_author'].value_counts()

language_author
bn    204278
ar       287
en         4
id         3
Name: count, dtype: int64

In [ ]:
for language in df_bn['language_author'].value_counts().index:
    if language == 'bn' or language == 'ar':
        continue
    else:
        print(f"Correcting Language: {language}")
        filt = (df_bn['language_author'] == language, 'author')
        df_bn.loc[filt] = df_bn.loc[filt].apply(translate_to_bangla)

print("\nDone")

Correcting Language: en
Correcting Language: id

Done

In [ ]:
df_bn.loc[df_bn['language_author'] == 'id', 'author'] = df_bn.loc[df_bn['language_author'] == 'id', 'author'].apply(translate_from_id)

In [ ]:
df_bn['language_author'] = df_bn['author'].apply(detect_language)
df_bn['language_author'].value_counts()

language_author
bn    204266
ar       301
en         5
Name: count, dtype: int64

In [ ]:
# let's see the names with arabic ones

for idx, names in enumerate(df_bn.loc[df_bn['language_author'] == 'ar', 'author']):
    print(f"{idx} | {names}")

0 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
1 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
2 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
3 | القاضي ناصر الدين عبد الله بن عمر البيضاوي (কাজী নাসিরুদ্দিন আব্দুল্লাহ বিন আমর বায়যাবী)
4 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
5 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
6 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
7 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
8 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
9 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
10 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
11 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
12 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
13 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
14 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
15 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
16 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
17 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
18 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
19 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
20 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
21 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
22 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
23 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
24 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
25 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
26 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
27 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
28 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
29 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
30 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
31 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
32 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
33 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
34 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
35 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
36 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
37 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
38 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
39 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
40 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
41 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
42 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
43 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
44 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
45 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
46 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
47 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
48 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
49 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
50 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
51 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
52 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
53 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
54 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
55 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
56 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
57 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
58 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
59 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
60 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
61 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
62 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
63 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
64 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
65 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
66 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
67 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
68 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
69 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
70 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
71 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
72 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
73 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
74 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
75 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
76 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
77 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
78 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
79 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
80 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
81 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
82 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
83 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
84 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
85 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
86 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
87 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
88 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
89 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
90 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
91 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
92 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
93 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
94 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
95 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
96 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
97 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
98 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
99 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
100 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
101 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
102 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
103 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
104 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
105 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
106 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
107 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
108 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
109 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
110 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
111 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
112 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
113 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
114 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
115 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
116 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
117 | مكتبة الحراء (মাকতাবাতুল হেরা)
118 | مكتبة الحراء (মাকতাবাতুল হেরা)
119 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
120 | مكتبة الحراء (মাকতাবাতুল হেরা)
121 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
122 | مكتبة الحراء (মাকতাবাতুল হেরা)
123 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
124 | مكتبة الحراء (মাকতাবাতুল হেরা)
125 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
126 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
127 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
128 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
129 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
130 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
131 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
132 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
133 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
134 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
135 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
136 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
137 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
138 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
139 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
140 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
141 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
142 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
143 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
144 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
145 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
146 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
147 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
148 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
149 | القاضي ناصر الدين عبد الله بن عمر البيضاوي (কাজী নাসিরুদ্দিন আব্দুল্লাহ বিন আমর বায়যাবী)
150 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
151 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
152 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
153 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
154 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
155 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
156 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
157 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
158 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
159 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
160 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
161 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
162 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
163 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
164 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
165 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
166 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
167 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
168 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
169 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
170 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
171 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
172 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
173 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
174 | (الامام مالك بن آنس) ইমাম মালেক বিন আনাছ (রহ.)
175 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
176 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
177 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
178 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
179 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
180 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
181 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
182 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
183 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
184 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
185 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
186 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
187 | مفتي محمد كفايت الله (মুফতী মুহাম্মাদ কিফায়াতুল্লাহ)
188 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
189 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
190 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
191 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
192 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
193 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
194 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
195 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
196 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
197 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
198 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
199 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
200 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
201 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
202 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
203 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
204 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
205 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
206 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
207 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
208 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
209 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
210 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
211 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
212 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
213 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
214 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
215 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
216 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
217 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
218 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
219 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
220 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
221 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
222 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
223 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
224 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
225 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
226 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
227 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
228 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
229 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
230 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
231 | حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)
232 | (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী

In [ ]:
# changing this name حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.) (সম্পাদক) to ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)

df_bn.loc[df_bn['author'] == 'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.) (সম্পাদক)', 'author'] = "হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ."

In [ ]:
# no more
df_bn.loc[df_bn['author'] == 'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.) (সম্পাদক)', 'author'].shape

(0,)

## Fixing the mixed language in author names (Arabic and Bangla)

In [ ]:
df_bn.loc[df_bn['language_author'] == 'ar', 'author']

1212      حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল...
5222      حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল...
5224      حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল...
5537      القاضي ناصر الدين عبد الله بن عمر البيضاوي (কা...
5563      حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল...
                                ...
191114    (شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলা...
191571    حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল...
191576    حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল...
194455    حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল...
195735    حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল...
Name: author, Length: 301, dtype: object

In [ ]:
filt = (df_bn['language_author'] == 'ar', 'author')
df_bn.loc[filt] = df_bn.loc[filt].apply(correct_author_names)

In [ ]:
for idx, name in enumerate(df_bn.loc[filt]):
    print(f"{idx} | {name}")

0 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
1 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
2 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
3 | কাজী নাসিরুদ্দিন আব্দুল্লাহ বিন আমর বায়যাবী
4 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
5 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
6 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
7 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
8 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
9 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
10 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
11 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
12 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
13 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
14 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
15 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
16 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
17 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
18 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
19 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
20 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
21 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
22 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
23 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
24 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
25 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
26 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
27 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
28 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
29 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
30 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
31 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
32 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
33 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
34 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
35 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
36 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
37 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
38 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
39 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
40 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
41 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
42 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
43 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
44 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
45 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
46 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
47 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
48 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
49 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
50 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
51 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
52 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
53 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
54 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
55 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
56 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
57 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
58 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
59 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
60 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
61 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
62 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
63 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
64 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
65 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
66 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
67 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
68 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
69 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
70 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
71 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
72 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
73 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
74 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
75 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
76 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
77 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
78 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
79 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
80 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
81 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
82 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
83 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
84 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
85 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
86 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
87 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
88 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
89 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
90 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
91 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
92 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
93 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
94 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
95 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
96 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
97 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
98 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
99 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
100 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
101 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
102 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
103 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
104 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
105 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
106 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
107 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
108 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
109 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
110 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
111 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
112 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
113 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
114 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
115 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
116 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
117 | মাকতাবাতুল হেরা
118 | মাকতাবাতুল হেরা
119 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
120 | মাকতাবাতুল হেরা
121 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
122 | মাকতাবাতুল হেরা
123 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
124 | মাকতাবাতুল হেরা
125 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
126 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
127 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
128 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
129 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
130 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
131 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
132 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
133 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
134 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
135 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
136 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
137 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
138 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
139 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
140 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
141 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
142 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
143 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
144 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
145 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
146 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
147 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
148 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
149 | কাজী নাসিরুদ্দিন আব্দুল্লাহ বিন আমর বায়যাবী
150 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
151 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
152 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
153 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
154 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
155 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
156 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
157 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
158 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
159 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
160 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
161 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
162 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
163 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
164 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
165 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
166 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
167 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
168 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
169 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
170 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
171 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
172 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
173 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
174 | ইমাম মালেক বিন আনাছ রহ
175 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
176 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
177 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
178 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
179 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
180 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
181 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
182 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
183 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
184 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
185 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
186 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
187 | মুফতী মুহাম্মাদ কিফায়াতুল্লাহ
188 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
189 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
190 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
191 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
192 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
193 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
194 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
195 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
196 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
197 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
198 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
199 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
200 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
201 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
202 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
203 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
204 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
205 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
206 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
207 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
208 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
209 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
210 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
211 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
212 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
213 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
214 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
215 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
216 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
217 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
218 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
219 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
220 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
221 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
222 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
223 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
224 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
225 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
226 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
227 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
228 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
229 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
230 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
231 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
232 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
233 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
234 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
235 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
236 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
237 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
238 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
239 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
240 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
241 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
242 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
243 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
244 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
245 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
246 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
247 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
248 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
249 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
250 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
251 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
252 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
253 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
254 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
255 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
256 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
257 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
258 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
259 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
260 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
261 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
262 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
263 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
264 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
265 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
266 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
267 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
268 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
269 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
270 | কাজী নাসিরুদ্দিন আব্দুল্লাহ বিন আমর বায়যাবী
271 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
272 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
273 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
274 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
275 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
276 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
277 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
278 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
279 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
280 | ড মাহমুদ আত্তাহ্হান
281 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
282 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
283 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
284 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
285 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
286 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
287 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
288 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
289 | ডক্টর মোস্তফা আস সাবায়ী
290 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
291 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
292 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
293 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
294 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
295 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
296 | শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী
297 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
298 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
299 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ
300 | হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ

## Fixing the mixed language in author names (English and Bangla)

In [ ]:
filt = (df_bn['language_author'] == 'en', 'author')

In [ ]:
df_bn.loc[filt] = df_bn.loc[filt].apply(correct_author_names)

In [ ]:
for idx, name in enumerate(df_bn.loc[filt]):
    print(f"{idx} | {name}")

0 | ড জাহিদুজ্জামান
1 | ড জাহিদুজ্জামান
2 | ড জাহিদুজ্জামান
3 | ড জাহিদুজ্জামান
4 | জসিম চৌধুরী

In [ ]:
df_bn['language_author'] = df_bn['author'].apply(detect_language)

In [ ]:
df_bn['language_author'].value_counts()

language_author
bn    204423
ar       149
Name: count, dtype: int64

In [ ]:
df_bn.loc[df_bn['language_author'] == 'ar', 'author'].values

array(['حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       '(شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       '(شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       '(شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'مكتبة الحراء (মাকতাবাতুল হেরা)', 'مكتبة الحراء (মাকতাবাতুল হেরা)',
       'مكتبة الحراء (মাকতাবাতুল হেরা)', 'مكتبة الحراء (মাকতাবাতুল হেরা)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       '(شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       '(شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       '(شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       '(شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী',
       'الشيخ محمد علي الصابوني ( আশ শাইখ মুহাম্মাদ আলী আস সাবুনী)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       '(شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী',
       '(شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী',
       'شيخ الاسلام ابن تيمية (শাইখুল ইসলাম তাকিউদ্দিন ইবনে তাইমিয়া)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       '(شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       '(شيخ الاسلام مفتي محمد تقي عثماني) শাইখুল ইসলাম মুফতী মুহাম্মাদ তাকী উসমানী',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'القاضي ناصر الدين عبد الله بن عمر البيضاوي (কাজী নাসিরুদ্দিন আব্দুল্লাহ বিন আমর বায়যাবী)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'الامام ابو زكريا يحيح بن شرف النووي (ইমাম আবু জাকারিয়া ইয়াহিয়া বিন শরফুন নবুবী)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)',
       'حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল উম্মত মাওলানা আশরাফ আলী থানভী রহ.)'],
      dtype=object)

 So there were other mixed language values that the language detect couldn't detect at first time

## Fixing all author names (keeping only with bangla letters)

In [ ]:
df_bn.loc[:, 'author'] = df_bn['author'].apply(correct_author_names)

In [ ]:
df_bn['language_author'] = df_bn['author'].apply(detect_language)

In [ ]:
df_bn['language_author'].value_counts()

language_author
bn    204572
Name: count, dtype: int64

All Bangla! yay!

In [ ]:
df_bn.to_csv("rokomari_books_only_bangla_v2.csv", index=False)